version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  sunbird_build_json:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: node --version
          name: Check node version
      - run:
          name: Build and Upload
          command: |
            if [ -z $CIRCLE_PR_NUMBER ]; then
              npm run build:publish
            else
              echo "Skipping Build and Upload"
            fi

workflows:
    version: 2
    sunbird_resource_bundles:
      jobs:
        - sunbird_build_json