version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  sunbird_build_json:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: node --version
          name: Check node version
      - run:
          name: "Setup custom ENV variables"
          command: npm run build:publish

workflows:
    version: 2
    sunbird_resource_bundles:
      jobs:
        - sunbird_build_json